#!/bin/bash

#install docker 
curl -s https://get.docker.com/ | bash
usermod -aG docker krack


#install sublime text
add-apt-repository ppa:webupd8team/sublime-text-3 && sudo apt-get update && sudo apt-get install sublime-text-installer

#install travis cli
gem install travis --no-rdoc --no-ri

echo "install done"



