sudo: required
language: node_js
before_script:
- sed -i 's/$TRAVIS_TAG/'${TRAVIS_TAG:-${TRAVIS_JOB_NUMBER:-0}}'/g' ./magic-package-workstation/DEBIAN/control
- sed -i 's/$TRAVIS_TAG/'${TRAVIS_TAG:-${TRAVIS_JOB_NUMBER:-0}}'/g' ./magic-package-workstation/usr/local/bin/magic-package-workstation
script:
- dpkg-deb --build magic-package-workstation
deploy:
- provider: packagecloud
  repository: magic-package-beta
  username: krack
  token:
    secure: M97Gw7cUo59FkAaEYsuON6htejQ5kr5Cj1MeIJVyyS632zfXsYzaOpUrgIj8F2PEdopcZQGMawWpabKKc+5cTwHM6irqRJE2z7Q6CpyG/9OtTHngRoyz++cklASiFHebW0f8TtPEru7myJGN8FecQIw9q1xCxxx3xX+NGAU+tCuEEB9vjgoZZvFcm0VeJsd38Cu4CZk5352yeZMCXnGy98dvA4Qh04NA4BiF8h5tfFd7tpWxD2K5EAnwLF7ib0plpnVl3QGKrKolB9wFgMgoODAeDCS4s55fQzi/3Cludo6FvmleO4DgfDG6msj5NoxKl0J4pZnbPpFER5tvd4bRQYURR79VsIu3kQByAjpWr8hF517joGfnmJdy2Xl9sAZW553JQZzwvzD4MYMuzPw2hyHWhDu4mBO59wDRYh6VRYpidvvCrbPQGftAqlfn0RusGlrBSxbDsV4wyLvELdZN6akf4G4KoiwUstkhSdHckYP5CuMB89W5lyS7wIs2f5oUy968QLGv1Sj/ZXMlIHlpg+FRjsNNqboZishKc431B9MFJFAA5PmJ6SwrYJZxrKvv1EoWifZYUdcur7rmbtalk0w7EJI1kecoRJFLDcUBpHnITGDnyZTnRj0Jzcfxzkk4iIHj7R1Nwp3VQiPTG5aoJ1ff89X03Cb3yvn7v9pE0Bk=
  dist: ubuntu/cosmic
  skip_cleanup: true
  on:
    tags: false
- provider: packagecloud
  repository: magic-package
  username: krack
  token:
    secure: M97Gw7cUo59FkAaEYsuON6htejQ5kr5Cj1MeIJVyyS632zfXsYzaOpUrgIj8F2PEdopcZQGMawWpabKKc+5cTwHM6irqRJE2z7Q6CpyG/9OtTHngRoyz++cklASiFHebW0f8TtPEru7myJGN8FecQIw9q1xCxxx3xX+NGAU+tCuEEB9vjgoZZvFcm0VeJsd38Cu4CZk5352yeZMCXnGy98dvA4Qh04NA4BiF8h5tfFd7tpWxD2K5EAnwLF7ib0plpnVl3QGKrKolB9wFgMgoODAeDCS4s55fQzi/3Cludo6FvmleO4DgfDG6msj5NoxKl0J4pZnbPpFER5tvd4bRQYURR79VsIu3kQByAjpWr8hF517joGfnmJdy2Xl9sAZW553JQZzwvzD4MYMuzPw2hyHWhDu4mBO59wDRYh6VRYpidvvCrbPQGftAqlfn0RusGlrBSxbDsV4wyLvELdZN6akf4G4KoiwUstkhSdHckYP5CuMB89W5lyS7wIs2f5oUy968QLGv1Sj/ZXMlIHlpg+FRjsNNqboZishKc431B9MFJFAA5PmJ6SwrYJZxrKvv1EoWifZYUdcur7rmbtalk0w7EJI1kecoRJFLDcUBpHnITGDnyZTnRj0Jzcfxzkk4iIHj7R1Nwp3VQiPTG5aoJ1ff89X03Cb3yvn7v9pE0Bk=
  dist: ubuntu/cosmic
  skip_cleanup: true
  on:
    tags: true
